### ISSUE TITLE
Dependency on   "zlib"

### ISSUE THREAD

**Issue by buymybm100** [yasir095/shopwave-oauth-client#1]
"zlib" is now obsolete. Will you be updating package.json to use "node-gyp"  ?
Many Thanks.

**Comment by yasir095** [comment]
At the moment zlib is supported by nodeJs so there is no need for a change unless some better compression library is available for node.
Thanks

**Comment by buymybm100** [comment]
Hi, is this Client still usable ?  I am getting an error about ZLIB when I run 
$ npm install shopwave-oauth-client 

> zlib@1.0.5 preinstall /Users/dev1/dev/test/node_modules/.staging/zlib-934e18d3
> node-waf clean || true; node-waf configure build

sh: node-waf: command not found
sh: node-waf: command not found
test@1.0.0 /Users/dev1/dev/test
└── request@2.83.0  extraneous

npm WARN test@1.0.0 No repository field.
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "shopwave-oauth-client"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! zlib@1.0.5 preinstall: `node-waf clean || true; node-waf configure build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the zlib@1.0.5 preinstall script 'node-waf clean || true; node-waf configure build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zlib package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf clean || true; node-waf configure build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zlib
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zlib
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dev1/dev/test/npm-debug.log

Any ideas ?
I am using  node v6.11.0  and npm 3.10.10
