### ISSUE TITLE
Can't install this package

### ISSUE THREAD

**Issue by buymybm100** [yasir095/shopwave-oauth-client#2]
Hi - I am getting a **node-waf: command not found** error when running npm install. 
I have installed 'node-waf' but that didn't help.

Can someone help ? 

Many Thanks,
Beemer

$ npm init
$ npm install node-waf
$ npm install shopwave-oauth-client

> zlib@1.0.5 preinstall /Users/buymybm100/dev/test/aa/node_modules/.staging/zlib-54b0f087
> node-waf clean || true; node-waf configure build

sh: node-waf: command not found
sh: node-waf: command not found
aa@1.0.0 /Users/buymybm100/dev/test/aa
└── request@2.83.0  extraneous

npm WARN aa@1.0.0 No description
npm WARN aa@1.0.0 No repository field.
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "shopwave-oauth-client"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! zlib@1.0.5 preinstall: `node-waf clean || true; node-waf configure build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the zlib@1.0.5 preinstall script 'node-waf clean || true; node-waf configure build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zlib package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf clean || true; node-waf configure build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zlib
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zlib
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/buymybm100/dev/test/aa/npm-debug.log

**Comment by yasir095** [comment]
Just try with the sudo npm install

**Comment by buymybm100** [comment]
Hi Yasir, 

Thanks for that. It worked with 'sudo' on my local machine.  However, I use Heroku as a production environment and 'sudo' isn't allowed. 

Is there another way without using 'sudo' ?

Best regards,
Beemer

**Comment by yasir095** [comment]
Hi Beemer, not sure I have to look into that, could be because of old dependencies. I'll try it on my system and will let you know if there is a fix.

Thanks

**Comment by buymybm100** [comment]
Thanks Yasir, much appreciated.

**Comment by yasir095** [comment]
Closing this issue now.
